#
# This module is provided as LIBCURL_USE_FILE by LIBCURLConfig.cmake.  
# It can be INCLUDEd in a project to load the needed compiler and linker
# settings to use LIBCURL:
#   FIND_PACKAGE(LIBCURL REQUIRED)
#   INCLUDE(${LIBCURL_USE_FILE})
#

IF(NOT LIBCURL_USE_FILE_INCLUDED)
  SET(LIBCURL_USE_FILE_INCLUDED 1)

  # Load the compiler settings used for LIBCURL.
  #IF(LIBCURL_BUILD_SETTINGS_FILE)
    #INCLUDE(${CMAKE_ROOT}/Modules/CMakeImportBuildSettings.cmake)
    #CMAKE_IMPORT_BUILD_SETTINGS(${LIBCURL_BUILD_SETTINGS_FILE})
  #ENDIF(LIBCURL_BUILD_SETTINGS_FILE)

  # Add compiler flags needed to use LIBCURL.
  #SET(CMAKE_C_FLAGS 
    #"${CMAKE_C_FLAGS} ${LIBCURL_REQUIRED_C_FLAGS}")
  #SET(CMAKE_CXX_FLAGS 
    #"${CMAKE_CXX_FLAGS} ${LIBCURL_REQUIRED_CXX_FLAGS}")
  #SET(CMAKE_EXE_LINKER_FLAGS 
    #"${CMAKE_EXE_LINKER_FLAGS} ${LIBCURL_REQUIRED_EXE_LINKER_FLAGS}")
  #SET(CMAKE_SHARED_LINKER_FLAGS 
    #"${CMAKE_SHARED_LINKER_FLAGS} ${LIBCURL_REQUIRED_SHARED_LINKER_FLAGS}")
  #SET(CMAKE_MODULE_LINKER_FLAGS 
    #"${CMAKE_MODULE_LINKER_FLAGS} ${LIBCURL_REQUIRED_MODULE_LINKER_FLAGS}")

  # Add include directories needed to use LIBCURL.
  INCLUDE_DIRECTORIES(${LIBCURL_INCLUDE_DIRS})

  # Add link directories needed to use LIBCURL.
  LINK_DIRECTORIES(${LIBCURL_LIBRARY_DIRS})

  #ADD_DEFINITIONS(-DHAVE_CONFIG_H)

  # Add cmake module path.
  #SET(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${LIBCURL_CMAKE_DIR}")

ENDIF(NOT LIBCURL_USE_FILE_INCLUDED)
