#
# Check the speed of the main CPU
#
# VARIABLE - variable to store the result to
#

MACRO(BatchMake_GET_CPU_INFO CPU_SPEED_MHZ_VAR CPU_NB_PHYSICAL_VAR CPU_NB_LOGICAL_VAR )

  IF(NOT DEFINED HAVE_${CPU_SPEED_MHZ_VAR})

    IF(NOT BatchMake_GET_CPU_INFO_EXE)
	  MESSAGE(FATAL_ERROR "BatchMake_GET_CPU_INFO_EXE is not defined!")
    ELSE(NOT BatchMake_GET_CPU_INFO_EXE)

      MESSAGE(STATUS "Check the speed of the main CPU...")

      EXECUTE_PROCESS(COMMAND ${BatchMake_GET_CPU_INFO_EXE}
        OUTPUT_VARIABLE OUTPUT
        RESULT_VARIABLE RESULT)

      SET(HAVE_${CPU_SPEED_MHZ_VAR} ${RESULT} CACHE INTERNAL "")

      IF(NOT OUTPUT OR NOT RESULT)
	    MESSAGE(FATAL_ERROR "GET_CPU_INFO ERROR:\n${OUTPUT}")
      ELSE(NOT OUTPUT OR NOT RESULT)

        # CPU speed
        STRING(REGEX MATCH "CPU_SPEED_MHZ=[A-Z0-9]+" OUTPUT_CPU ${OUTPUT})
        IF(OUTPUT_CPU)
          STRING(LENGTH  ${OUTPUT_CPU} OUTPUT_CPU_LENGTH)
          MATH(EXPR CPU_SIZE "${OUTPUT_CPU_LENGTH}-14")
          STRING(SUBSTRING ${OUTPUT_CPU} 14 ${CPU_SIZE} ${CPU_SPEED_MHZ_VAR})
        ELSE(OUTPUT_CPU)
          SET(${CPU_SPEED_MHZ_VAR} 0)
        ENDIF(OUTPUT_CPU)
      
        # Number of physical CPUs
        STRING(REGEX MATCH "CPU_PHYSICAL_CPUS=[A-Z0-9]+" OUTPUT_CPU ${OUTPUT})
        IF(OUTPUT_CPU)
          STRING(LENGTH  ${OUTPUT_CPU} OUTPUT_CPU_LENGTH)
          MATH(EXPR CPU_SIZE "${OUTPUT_CPU_LENGTH}-18")
          STRING(SUBSTRING ${OUTPUT_CPU} 18 ${CPU_SIZE} ${CPU_NB_PHYSICAL_VAR})
        ELSE(OUTPUT_CPU)
          SET(${CPU_NB_PHYSICAL_VAR} 0)
        ENDIF(OUTPUT_CPU)
      
        # Number of logical CPUs
        STRING(REGEX MATCH "CPU_LOGICAL_CPUS=[A-Z0-9]+" OUTPUT_CPU ${OUTPUT})
        IF(OUTPUT_CPU)
          STRING(LENGTH  ${OUTPUT_CPU} OUTPUT_CPU_LENGTH)
          MATH(EXPR CPU_SIZE "${OUTPUT_CPU_LENGTH}-17")
          STRING(SUBSTRING ${OUTPUT_CPU} 17 ${CPU_SIZE} ${CPU_NB_LOGICAL_VAR})
        ELSE(OUTPUT_CPU)
          SET(${CPU_NB_LOGICAL_VAR} 0)
        ENDIF(OUTPUT_CPU)
        
      ENDIF(NOT OUTPUT OR NOT RESULT)
      
    ENDIF(NOT BatchMake_GET_CPU_INFO_EXE)

  ENDIF(NOT DEFINED HAVE_${CPU_SPEED_MHZ_VAR})

ENDMACRO(BatchMake_GET_CPU_INFO)
