#
# Check the total physical memory available on the system
#
# VARIABLE - variable to store the result to
#

MACRO(BatchMake_GET_MEMORY_INFO MEMORY_TOTAL_PHYSICAL_MB_VAR)

  IF(NOT DEFINED HAVE_${MEMORY_TOTAL_PHYSICAL_MB_VAR})

    IF(NOT BatchMake_GET_MEMORY_INFO_EXE)
	  MESSAGE(FATAL_ERROR "BatchMake_GET_MEMORY_INFO_EXE is not defined!")
    ELSE(NOT BatchMake_GET_MEMORY_INFO_EXE)

      MESSAGE(STATUS 
        "Check the total amount of memory on the system...")

      EXECUTE_PROCESS(COMMAND ${BatchMake_GET_MEMORY_INFO_EXE}
        OUTPUT_VARIABLE OUTPUT
        RESULT_VARIABLE RESULT)

      SET(HAVE_${MEMORY_TOTAL_PHYSICAL_MB_VAR} ${RESULT} CACHE INTERNAL "")

      IF(NOT OUTPUT OR NOT RESULT)
	    MESSAGE(FATAL_ERROR "GET_MEMORY_INFO ERROR:\n${OUTPUT}")
      ELSE(NOT OUTPUT OR NOT RESULT)

        STRING(REGEX MATCH "PHYSICAL_MEMORY_MB=[-A-Z0-9]+" OUTPUT_MEM ${OUTPUT})
        STRING(LENGTH ${OUTPUT_MEM} OUTPUT_MEM_LENGTH)
        MATH(EXPR MEM_SIZE "${OUTPUT_MEM_LENGTH}-19")
        STRING(SUBSTRING ${OUTPUT_MEM} 19 ${MEM_SIZE} ${MEMORY_TOTAL_PHYSICAL_MB_VAR})
      ENDIF(NOT OUTPUT OR NOT RESULT)
      
    ENDIF(NOT BatchMake_GET_MEMORY_INFO_EXE)
    
  ENDIF(NOT DEFINED HAVE_${MEMORY_TOTAL_PHYSICAL_MB_VAR})

ENDMACRO(BatchMake_GET_MEMORY_INFO)
